import { sql } from 'drizzle-orm';
import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
// MEDIA_CONTENT_TYPES itself lives in packages/contracts — see field-definitions.ts for why.
import type { MediaContentType } from '@kenresoft-cms/contracts';

import { mediaFolders } from './media-folders';

export type { MediaContentType };

export const media = sqliteTable(
  'media',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    // R2 object key — generated by the application (§14), never derived from a client-supplied
    // filename. Unaffected by folders: moving a media item between folders is a plain
    // `folderId` update, never an R2 key rename/copy.
    key: text('key').notNull().unique(),
    filename: text('filename').notNull(),
    contentType: text('content_type').notNull().$type<MediaContentType>(),
    size: integer('size').notNull(),
    // Null only if the file's dimensions couldn't be parsed from its bytes at all (every
    // supported format — PNG/GIF/JPEG/WebP — has parsing; apps/api/src/lib/image-metadata.ts).
    width: integer('width'),
    height: integer('height'),
    altText: text('alt_text'),
    // Null = unfiled/root — every pre-existing media row keeps working unmodified, and
    // "no folder" stays a valid, first-class state rather than requiring migration into a
    // synthetic default folder. `onDelete: 'set null'` so deleting a folder never deletes or
    // orphans the files in it — they simply become unfiled again.
    folderId: text('folder_id').references(() => mediaFolders.id, { onDelete: 'set null' }),
    createdAt: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
    updatedAt: integer('updated_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (table) => [index('media_folder_id_idx').on(table.folderId)],
);

export type Media = typeof media.$inferSelect;
export type NewMedia = typeof media.$inferInsert;
