import { desc, eq, session } from '@kenresoft/database';
import type { Database } from '@kenresoft/database';

// auth.ts is generated by @better-auth/cli (apps/api/src/lib/auth-options.ts's pinned-version
// note) and doesn't export a Session type itself — inferred here instead of hand-adding one to
// a generated file.
export type Session = typeof session.$inferSelect;

export function listSessionsForUser(db: Database, userId: string): Promise<Session[]> {
  return db.query.session.findMany({
    where: eq(session.userId, userId),
    orderBy: desc(session.updatedAt),
  });
}

export function getSessionById(db: Database, id: string): Promise<Session | undefined> {
  return db.query.session.findFirst({ where: eq(session.id, id) });
}

// Deleting the row is enough to kill the session — better-auth's getSession looks up the
// session by its token against this same table on every authenticated request, so a missing
// row is indistinguishable from an expired one. No better-auth admin-plugin dependency needed
// (deliberately not used here, apps/api/src/lib/auth-options.ts) for something this direct.
export async function deleteSession(db: Database, id: string): Promise<void> {
  await db.delete(session).where(eq(session.id, id));
}
